name: levelup
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  http:  ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/podium.png
    - assets/images/logo.png
    - assets/iframe.html
    - assets/viewer.html
    - assets/src/index.js
    - assets/animations/f_idle.fbx
    - assets/animations/m_idle.fbx

